### ISSUE TITLE
ERROR: please check

### ISSUE THREAD

**Issue by martinoli-f** [DataAccess2020/CE2_Martinoli_Travaglini#1]
Hi @simonetravaglini1 !! **:)** Sorry for bothering you, I was trying to get all the links from [this page of Beppe Grillo' blog](https://beppegrillo.it/un-mare-di-plastica-ci-sommergera/) using the rvest package, but I think I made a mistake. I can only see the titles of the links, not the actual links **:(** Can you please check this abf1cf1 and myabe try to fix it? thanks **:)**

**Comment by simonetravaglini1** [comment]
Hi dear @martinoli-f  :). i fixed the issues  using xml. please check the commit n° 0b37fd7. have a good day :)))
